# Generated by Django 4.2.23 on 2025-07-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ugc", "0002_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
